### ISSUE TITLE
Ptz optics module incomplete

### ISSUE THREAD

**Issue by MIXACHU** [bitfocus/companion-module-ptzoptics-visca#1] opened 2019-05-18 21:55 UTC
**Describe the feature**
There are lots of features missing in this module. One could help a lot to solve many, the OSD control ones. Through these  7 commands, one can easily change white balnce, shutter speed ...

**Is this platform dependent (windows, mac, ..)?**
No 
**If documentation is required to implement, do you know where to find it?**
https://cdn2.hubspot.net/hubfs/418770/PTZOptics%20Complete%20VISCA%20over%20IP%20Commands%20(Packet%20Sender).ini
 
**Usecases**
See above

**Comment by jswalden** [comment] 2024-05-07 00:14
OSD control actions and presets were added in #35 and are in the [3.0.0 release](https://github.com/bitfocus/companion-module-ptzoptics-visca/releases/tag/v3.0.0) (which will be in the next Companion release, or you can manually download and install it in Companion >=3.2 by following the instructions in release notes).

Beyond that, I don't think it's great from a project-management point of view to have issues that are this unspecific about an identified problem or the fixes requested -- because it's never quite clear when the issue is ultimately _done_.  Or whether it's even the right/best place to make any specific change, compared to a newer, narrowly targeted issue.

If there are specific things in docs that you want to send, feel free to point them out equally specifically in new issues.  🙂  (Or use the "Custom command" action to send any command you want that the module doesn't natively support.)  I'm going to close this one to keep the issue list more manageable.

**Closed by jswalden** 2024-05-07 00:14 UTC
