### ISSUE TITLE
Feature request: Set Instance Using Variable

### ISSUE THREAD

**Issue by hparsons56** [bitfocus/companion-module-ptzoptics-visca#23] opened 2023-02-04 23:01 UTC
I think it would be great if you could create an instance based on a variable name. Commands would then be sent to the IP address set in the variable name.

**Comment by jswalden** [comment] 2024-10-28 23:01
This is more or less a duplicate of the camera IP address half of #27.  For the reasons I [discuss](https://github.com/bitfocus/companion-module-ptzoptics-visca/issues/27#issuecomment-2442824076) there, it's not standard practice for one connection to represent multiple devices.  And as to the specific wording here, we need to keep in mind that a single instance of this module, a single connection, represents one persistent TCP connection -- for it to apply to multiple IP addresses you're starting to think of it in terms of having multiple TCP connections (that might or might not be persistent -- and if they're not, every action would have to initiate a new connection then promptly dropped when the action was complete).

I think if you want to really have a single action run parametrically across multiple devices where you select the right one at runtime, you should just do it using the button-pressing mechanism already built into Companion, with separate buttons replicating the same action upon different connections, then you pick among them with an index variable and a computed location of the button to press.  Put all the buttons in page 99 (or some page you never bring to fore), and go to town with that.

**Closed by jswalden** 2024-10-28 23:01 UTC
